#define _CRT_SECURE_NO_WARNINGS 
#include <iostream>
#include <string>
#include <math.h>
#include <Windows.h>
#include <cstdlib>
#include <algorithm>
#include <iomanip>
#include <string>
#include <conio.h>
#include <vector>
#include <string.h>
#include <fstream>
