#define _CRT_SECURE_NO_WARNINGS 
#define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
#include <iostream>
#include <fstream>
#include <filesystem>
#include <string>
#include <math.h>
#include <Windows.h>
#include <cstdlib>
#include <algorithm>
#include <iomanip>
#include <string>
#include <conio.h>
#include <vector>
#include <string.h>
#include <codecvt>
